### ISSUE TITLE
Question, does this related to std::io?

### ISSUE THREAD

**Issue by lygstate** [bincode-org/bincode-core#9]
I am looking for no_std  std::io alternative.

https://github.com/rust-lang/rust/pull/77781

**Comment by VictorKoenders** [comment]
Currently we have our own read traits: https://github.com/bincode-org/bincode-core/tree/master/src/traits
If the std::io::Read/Write traits get ported to core, or core gets some other Read/Write traits, we'd definitely be using those
There is also a crate called `core_io`, which might be a good option: https://docs.rs/core_io

Currently we're putting down the groundworks for a `no_std` and `alloc` version of bincode until the read/write traits get settled
